name: 'Build ASP 3.1'
description: 'Builds ASP Core 3.1 WebApps'
inputs:
  app-name:
    description: 'Name for artifacts and Docker images'
    required: true
    default: 'aspapp'
  myget-pre-auth-url:
    default: ""
  docker-username:
    required: true
  docker-password:
    required: true
  github-token:
    required: true
runs:
  using: 'node12'
  main: 'index.js'