name: 'Build ASP 3.1'
description: 'Builds ASP Core 3.1 WebApps'
inputs:
  app-name:
    description: 'Name for artifacts and Docker images'
    required: true
    default: 'aspapp'
  myget-pre-auth-url:
    default: ""
  docker-username:
    required: true
  docker-password:
    required: true
  build-configuration:
    description: 'Build configuration'
    required: false
    default: 'debug'
  check-out-path:
    description: 'Check-Out Path'
    required: false
    default: ''
outputs:
  version:
    description: 'Build version'
  artifact-name:
    description: 'Name of uploaded artifact'
runs:
  using: 'node12'
  main: 'index.js'